Replace `icat` `imagecat` symlink with wrapper script including `curl`.
This is a wrapper that supports existing `imagecat` behavior and adds
the ability to display images using URLs.

diff --git a/bin/icat b/bin/icat
--- a/bin/icat
+++ b/bin/icat
@@ -1,1 +1,152 @@
-imagecat
+#!/usr/bin/env bash
+#  _           _
+# (_) ___ __ _| |_
+# | |/ __/ _` | __|
+# | | (_| (_| | |_
+# |_|\___\__,_|\__|
+#
+# `imagecat` with curl.
+#
+# Display an image by providing a filename, URL, or standard input stream.
+#
+# Based on Bash Boilerplate: https://github.com/alphabetum/bash-boilerplate
+#
+# Copyright (c) 2015 William Melody • hi@williammelody.com
+
+set -o nounset
+set -o errexit
+set -o pipefail
+IFS=$'\n\t'
+
+###############################################################################
+# Dependency / Platform Check
+###############################################################################
+
+# command_exists()
+#
+# Usage:
+#   command_exists "command_name"
+#
+# Returns:
+#   0  If the command exists in the current environment.
+#   1  If not.
+command_exists() {
+  hash "$1" 2>/dev/null
+}
+
+if ! command_exists "imagecat"
+then
+  printf "imagecat not found on this system.\n"
+  exit 1
+fi
+
+###############################################################################
+# Environment
+###############################################################################
+
+# $_ME
+#
+# Set to this program's basename.
+_ME=$(basename "$0")
+
+###############################################################################
+# Help
+###############################################################################
+
+read -r -d '' "_program_help" <<EOM || true
+ _           _
+(_) ___ __ _| |_
+| |/ __/ _\` | __|
+| | (_| (_| | |_
+|_|\___\__,_|\__|
+
+\`imagecat\` with curl.
+
+Display an image by providing a filename, URL, or standard input stream.
+
+Usage:
+  $_ME <filename>
+  $_ME <url>
+  cat <filename> | $_ME
+  $_ME -h | --help
+
+Options:
+  -h --help  Show this screen.
+EOM
+
+# _print_help()
+#
+# Usage: _print_help
+#
+# Print the program help information.
+_print_help() {
+  printf "%s\n" "$_program_help"
+}
+
+###############################################################################
+# Program Functions
+###############################################################################
+
+# _interactive_input()
+#
+# Usage:
+#   _interactive_input
+#
+# Returns:
+#   0  If the current input is interactive (eg, a shell).
+#   1  If the current input is stdin / piped input.
+_interactive_input() {
+  [[ -t 0 ]]
+}
+
+# _icat()
+#
+# Usage:
+#   _icat <filename>
+#   _icat <url>
+#   _icat <arguments>
+#   cat <filename> | _icat
+#
+# Description:
+_icat() {
+  if _interactive_input
+  then
+    local _source=${1:-}
+    local _url_regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
+    if [[ -z "$_source" ]]
+    then
+      $_ME -h
+    else
+      if [[ "$_source" =~ $_url_regex  ]]
+      then # if the source is a URL.
+        curl -Ls "$_source" | imagecat
+      else
+        cat "$_source" | imagecat
+      fi
+    fi
+  else
+    # Pass the pipe.
+    cat | imagecat
+  fi
+}
+
+###############################################################################
+# Main
+###############################################################################
+
+# _main()
+#
+# Usage:
+#   _main [<options>] [<arguments>]
+#
+# Description:
+#   Entry point for the program, handling basic option parsing and dispatching.
+_main() {
+  case "${1:-}" in
+    -h|--help)  _print_help     ;;
+    *)          _icat "$@"        ;;
+  esac
+}
+
+# Call `_main` after everything has been defined.
+_main "$@"
