Update rubocop to avoid circular reference.
Since the `rubocop` script is intended to wrap the next instance of
`rubocop` in the `$PATH`, the first `rubocop` reference is treated as
the wrapped executable.

diff --git a/bin/rubocop b/bin/rubocop
--- a/bin/rubocop
+++ b/bin/rubocop
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 ###############################################################################
 # rubocop wrapper
 #
@@ -18,11 +18,59 @@
 # - https://github.com/scrooloose/syntastic/wiki/Ruby%3A---rubocop
 # - https://gist.github.com/lcd047/96138909015f2f8d2d36
 ###############################################################################
-if [ $# -eq 1 -a x"$1" = x--version ]
+
+###############################################################################
+# Strict Mode
+###############################################################################
+
+set -o nounset
+set -o errexit
+set -o pipefail
+IFS=$'\n\t'
+
+###############################################################################
+# Program
+###############################################################################
+
+# __unwrap_rubocop()
+#
+# Usage:
+#   __unwrap_rubocop
+#
+# Description:
+#   Return the next `rubocop` in the `$PATH` that isn't this one.
+__unwrap_rubocop() {
+  local _rubocops=($(which -a rubocop))
+  local _other_rubocop=
+  for _element in "${_rubocops[@]}"
+  do
+    if [[ ! "$_element" == "$BASH_SOURCE" ]]
+    then
+      if [[ -z "$_other_rubocop" ]]
+      then
+        _other_rubocop="$_element"
+      fi
+    fi
+  done
+  printf "%s\n" "$_other_rubocop"
+}
+
+__unwrapped_rubocop=$(__unwrap_rubocop)
+
+# Exit if no other rubocop executable is found.
+if [[ -z "${__unwrapped_rubocop:-}" ]]
 then
-  rubocop "$@" 2>&1 | \
+  printf "rubocop not found.\n"
+  exit 1
+fi
+
+# If "--version" is passed as the first argument, return the version without
+# the unwanted warnings.
+if [ $# -eq 1 -a "${1:-}" = --version ]
+then
+  "$__unwrapped_rubocop" "$@" 2>&1 | \
     sed '/warning: parser\/current is loading parser\/ruby[0-9]*, which recognizes/d;
          /warning: [0-9.]*-compliant syntax, but you are running [0-9.]/d'
 else
-  exec rubocop "$@"
+  exec "$__unwrapped_rubocop" "$@"
 fi
