Generalize `rubocop` unwrapping to use as a reference for other scripts.

diff --git a/bin/rubocop b/bin/rubocop
--- a/bin/rubocop
+++ b/bin/rubocop
@@ -29,48 +29,58 @@ set -o pipefail
 IFS=$'\n\t'
 
 ###############################################################################
-# Program
+# Unwrap
 ###############################################################################
 
-# __unwrap_rubocop()
+# __unwrap()
 #
 # Usage:
-#   __unwrap_rubocop
+#   __unwrap
 #
 # Description:
-#   Return the next `rubocop` in the `$PATH` that isn't this one.
-__unwrap_rubocop() {
-  local _rubocops=($(which -a rubocop))
-  local _other_rubocop=
-  for _element in "${_rubocops[@]}"
+#   Return the next executable with the same basename as this script in the
+#   `$PATH`.
+__unwrap() {
+  local _basename
+  local _executables
+  local _next_executable
+
+  _basename=$(basename "$BASH_SOURCE")
+  _executables=($(which -a "${_basename:-}"))
+  for _element in "${_executables[@]}"
   do
     if [[ ! "$_element" == "$BASH_SOURCE" ]]
     then
-      if [[ -z "$_other_rubocop" ]]
+      if [[ -z "${_next_executable:-}" ]]
       then
-        _other_rubocop="$_element"
+        _next_executable="$_element"
       fi
     fi
   done
-  printf "%s\n" "$_other_rubocop"
+
+  # Exit if no other executable is found.
+  if [[ -z "${_next_executable:-}" ]]
+  then
+    printf "%s not found.\n" "${_basename:-}"
+    exit 1
+  else
+    printf "%s\n" "$_next_executable"
+  fi
 }
 
-__unwrapped_rubocop=$(__unwrap_rubocop)
+__unwrapped_executable=$(__unwrap)
 
-# Exit if no other rubocop executable is found.
-if [[ -z "${__unwrapped_rubocop:-}" ]]
-then
-  printf "rubocop not found.\n"
-  exit 1
-fi
+###############################################################################
+# Perform operations.
+###############################################################################
 
 # If "--version" is passed as the first argument, return the version without
 # the unwanted warnings.
 if [ $# -eq 1 -a "${1:-}" = --version ]
 then
-  "$__unwrapped_rubocop" "$@" 2>&1 | \
+  "$__unwrapped_executable" "$@" 2>&1 | \
     sed '/warning: parser\/current is loading parser\/ruby[0-9]*, which recognizes/d;
          /warning: [0-9.]*-compliant syntax, but you are running [0-9.]/d'
 else
-  "$__unwrapped_rubocop" "$@"
+  "$__unwrapped_executable" "$@"
 fi
