Unwrap `vim` by iterating over `which -a`.

diff --git a/bin/vim b/bin/vim
--- a/bin/vim
+++ b/bin/vim
@@ -5,14 +5,73 @@
 # A wrapper for vim commands.
 ###############################################################################
 
+###############################################################################
+# Strict Mode
+###############################################################################
+
+set -o nounset
+set -o errexit
+set -o pipefail
+IFS=$'\n\t'
+
+###############################################################################
+# Unwrap
+###############################################################################
+
+# __unwrap()
+#
+# Usage:
+#   __unwrap
+#
+# Description:
+#   Return the next executable with the same basename as this script in the
+#   `$PATH`.
+__unwrap() {
+  local _basename
+  local _executables
+  local _next_executable
+
+  _basename=$(basename "$BASH_SOURCE")
+  _executables=($(which -a "${_basename:-}"))
+  for _element in "${_executables[@]}"
+  do
+    if ( \
+      [[ ! "$_element" == "$BASH_SOURCE" ]] &&
+      [[ "$_element" =~ ^/.* ]]
+    )
+    then
+      if [[ -z "${_next_executable:-}" ]]
+      then
+        _next_executable="$_element"
+      fi
+    fi
+  done
+
+  # Exit if no other executable is found.
+  if [[ -z "${_next_executable:-}" ]]
+  then
+    printf "%s not found.\n" "${_basename:-}"
+    exit 1
+  else
+    printf "%s\n" "$_next_executable"
+  fi
+}
+
+__unwrapped_executable=$(__unwrap)
+
+###############################################################################
+# Wrapper operations
+###############################################################################
+
 # Use `nvim` for all vim operations if it is present in the $PATH. Otherwise,
 # use regular `vim`.
 #
 # `exec` tells the shell to just give control to the executable without
 # forking. See: http://stackoverflow.com/a/1696062
 _nvim_path="$(which nvim)"
-if [ -e "$_nvim_path" ]; then
+if [[ -e "$_nvim_path" ]]
+then
   exec "$_nvim_path" "$@"
 else
-  exec "vim" "$@"
+  exec "$__unwrapped_executable" "$@"
 fi
