Update `vim` wrapper and nvim configuration for neovim 0.1.0.
The configuration for neovim has been moved to ~/.config/nvim:

https://neovim.io/doc/user/nvim_from_vim.html

In the current configuration this is not configured because vim uses the
janus distribution, which includes the ~/.janus directory as well as the
~/.vim.before and ~/.vim.after files, for which there is no immediately
obvious way to include in ~/.config/nvim. To avoid running nvim when
the configuration is not available at this location, check for it in the
`vim` wrapper and fall back to `vim` when it's missing.

diff --git a/bin/vim b/bin/vim
--- a/bin/vim
+++ b/bin/vim
@@ -35,10 +35,7 @@ __unwrap() {
   _executables=($(which -a "${_basename:-}"))
   for _element in "${_executables[@]}"
   do
-    if ( \
-      [[ ! "$_element" == "$BASH_SOURCE" ]] &&
-      [[ "$_element" =~ ^/.* ]]
-    )
+    if [[ ! "$_element" == "$BASH_SOURCE" ]] && [[ "$_element" =~ ^/.* ]]
     then
       if [[ -z "${_next_executable:-}" ]]
       then
@@ -67,12 +64,15 @@ __unwrap() {
 # NOTE:
 # - `exec` tells the shell to just give control to the executable without
 #   forking. See: http://stackoverflow.com/a/1696062
-# - the `||` style used for setting `$_nvim_path` and
-#   `__unwrapped_executable` handles the non-zero exit from `which nvim`
-#   when `nvim` is not found, which otherwise would exit the program due to
-#   the `set -o errexit` strictness setting.
-_nvim_path="$(which nvim)" || __unwrapped_executable=$(__unwrap)
-if [[ -e "$_nvim_path" ]]
+# - the `|| true` style used for setting `$_nvim_path` handles the non-zero
+#   exit from `which nvim` when `nvim` is not found, which otherwise would
+#   exit the program due to the `set -o errexit` strictness setting.
+#
+# More info about nvim configuration:
+# https://neovim.io/doc/user/nvim_from_vim.html
+_nvim_path="$(which nvim)" || true
+__unwrapped_executable="$(__unwrap)"
+if [[ -e "$_nvim_path" ]] && [[ -e "$HOME/.config/nvim" ]]
 then
   exec "$_nvim_path" "$@"
 else
